language: go

go:
    - 1.11

install: skip
script: skip

jobs:
    include:
    - stage: test
      script:
      - export GO111MODULE=on
      - make dependencies
      - export GOOS=linux
      - export GOARCH=amd64
      - make test
