language: go

go:
    - 1.8

env:
    - EXECUTABLE=gpio_client
    - EXECUTABLE=server
    - EXECUTABLE=tests

script:
    - mkdir -p $GOPATH/src/iosomething
    - rsync -az ${TRAVIS_BUILD_DIR}/ $GOPATH/src/iosomething/
    - export TRAVIS_BUILD_DIR=$GOPATH/src/iosomething
    - cd ${TRAVIS_BUILD_DIR}
    - make $EXECUTABLE