language: go

go:
    - 1.9

install: skip
script: skip

jobs:
    include:
    - stage: test
      script:
      - mkdir -p $GOPATH/src/chik
      - rsync -az ${TRAVIS_BUILD_DIR}/ $GOPATH/src/chik/
      - export TRAVIS_BUILD_DIR=$GOPATH/src/chik
      - cd ${TRAVIS_BUILD_DIR}
      - make dependencies
      - export GOOS=linux
      - export GOARCH=amd64
      - make test
    - stage: deploy
      if: tag IS present
      script:
      - mkdir -p $GOPATH/src/chik
      - rsync -az ${TRAVIS_BUILD_DIR}/ $GOPATH/src/chik/
      - export TRAVIS_BUILD_DIR=$GOPATH/src/chik
      - cd ${TRAVIS_BUILD_DIR}
      - make dependencies
      - export GOOS=linux
      - export GOARCH=amd64
      - make deploy
