// Code generated by "stringer -type=CommandType"; DO NOT EDIT.

package chik

import "strconv"

const _CommandType_name = "HeartbeatTypeDigitalCommandTypeTimerCommandTypeStatusRequestCommandTypeStatusReplyCommandTypeVersionRequestCommandTypeVersionReplyCommandTypeSunsetCommandTypemessageBound"

var _CommandType_index = [...]uint8{0, 13, 31, 47, 71, 93, 118, 141, 158, 170}

func (i CommandType) String() string {
	if i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
