// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package iosomething

import "strconv"

const _MsgType_name = "SimpleCommandTypeDigitalCommandTypeStatusIndicationTypeVersionIndicationTypeHeartbeatTypemessageBound"

var _MsgType_index = [...]uint8{0, 17, 35, 55, 76, 89, 101}

func (i MsgType) String() string {
	if i >= MsgType(len(_MsgType_index)-1) {
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
