// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package chik

import "strconv"

const _MsgType_name = "SimpleCommandTypeDigitalCommandTypeTimedCommandTypeStatusIndicationTypeVersionIndicationTypeHeartbeatTypemessageBound"

var _MsgType_index = [...]uint8{0, 17, 35, 51, 71, 92, 105, 117}

func (i MsgType) String() string {
	if i >= MsgType(len(_MsgType_index)-1) {
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
