// Code generated by "stringer -type=CommandType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeartbeatType-0]
	_ = x[DigitalCommandType-1]
	_ = x[AnalogCommandType-2]
	_ = x[StatusSubscriptionCommandType-3]
	_ = x[StatusNotificationCommandType-4]
	_ = x[VersionRequestCommandType-5]
	_ = x[VersionReplyCommandType-6]
	_ = x[ActionRequestCommandType-7]
	_ = x[ActionReplyCommandType-8]
	_ = x[StatusUpdateCommandType-9]
	_ = x[IODeviceStatusChangedCommandType-10]
	_ = x[AnyIncomingCommandType-11]
	_ = x[AnyOutgoingCommandType-12]
	_ = x[messageBound-13]
}

const _CommandType_name = "HeartbeatTypeDigitalCommandTypeAnalogCommandTypeStatusSubscriptionCommandTypeStatusNotificationCommandTypeVersionRequestCommandTypeVersionReplyCommandTypeActionRequestCommandTypeActionReplyCommandTypeStatusUpdateCommandTypeIODeviceStatusChangedCommandTypeAnyIncomingCommandTypeAnyOutgoingCommandTypemessageBound"

var _CommandType_index = [...]uint16{0, 13, 31, 48, 77, 106, 131, 154, 178, 200, 223, 255, 277, 299, 311}

func (i CommandType) String() string {
	if i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
