// Code generated by "stringer -type=CommandType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeartbeatType-0]
	_ = x[DigitalCommandType-1]
	_ = x[StatusSubscriptionCommandType-2]
	_ = x[StatusNotificationCommandType-3]
	_ = x[VersionRequestCommandType-4]
	_ = x[VersionReplyCommandType-5]
	_ = x[ActionRequestCommandType-6]
	_ = x[ActionReplyCommandType-7]
	_ = x[StatusUpdateCommandType-8]
	_ = x[IODeviceStatusChangedCommandType-9]
	_ = x[AnyIncomingCommandType-10]
	_ = x[AnyOutgoingCommandType-11]
	_ = x[messageBound-12]
}

const _CommandType_name = "HeartbeatTypeDigitalCommandTypeStatusSubscriptionCommandTypeStatusNotificationCommandTypeVersionRequestCommandTypeVersionReplyCommandTypeActionRequestCommandTypeActionReplyCommandTypeStatusUpdateCommandTypeIODeviceStatusChangedCommandTypeAnyIncomingCommandTypeAnyOutgoingCommandTypemessageBound"

var _CommandType_index = [...]uint16{0, 13, 31, 60, 89, 114, 137, 161, 183, 206, 238, 260, 282, 294}

func (i CommandType) String() string {
	if i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
