// Code generated by "stringer -type=CommandType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeartbeatType-0]
	_ = x[DigitalCommandType-1]
	_ = x[StatusSubscriptionCommandType-2]
	_ = x[StatusNotificationCommandType-3]
	_ = x[VersionRequestCommandType-4]
	_ = x[VersionReplyCommandType-5]
	_ = x[StatusUpdateCommandType-6]
	_ = x[IODeviceStatusChangedCommandType-7]
	_ = x[AnyIncomingCommandType-8]
	_ = x[AnyOutgoingCommandType-9]
	_ = x[messageBound-10]
}

const _CommandType_name = "HeartbeatTypeDigitalCommandTypeStatusSubscriptionCommandTypeStatusNotificationCommandTypeVersionRequestCommandTypeVersionReplyCommandTypeStatusUpdateCommandTypeIODeviceStatusChangedCommandTypeAnyIncomingCommandTypeAnyOutgoingCommandTypemessageBound"

var _CommandType_index = [...]uint8{0, 13, 31, 60, 89, 114, 137, 160, 192, 214, 236, 248}

func (i CommandType) String() string {
	if i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
